name: "Document Sync"
description: "Sync Documents between INT and a target Environment"
inputs:
  TARGET_ENVIRONMENT:
    required: true
    type: string
    description: The Environment to Copy Files into.
  STACK:
    required: false
    type: string
    description: The stack being deployed. (ie., 'epsam' or 'epsam-pr-123')

jobs:
  #  Download files from Environment
  download-source:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: int-documents
    steps:
      - name: Connect to Source Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: epsam-document-sync

      - name: Find Source Bucket by Partial Name
        id: find-source-bucket
        working-directory: .github/scripts
        run: ./find_bucket.sh "epsam-storagedocsbucketepsamdocs"

      - name: Download all Files from Source Bucket
        run: |
          mkdir ./s3-content
          aws s3 sync s3://${{ steps.find-source-bucket.outputs.BUCKET_NAME }} ./s3-content

      - name: Connect to Source Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets[format('{0}_CLOUD_FORMATION_DEPLOY_ROLE', inputs.TARGET_ENVIRONMENT)] }}
          role-session-name: epsam-document-sync

      - name: Find Destination Bucket by Partial Name
        id: find-destination-bucket
        working-directory: .github/scripts
        run: |
          # If PR is provided, use the PR pattern, otherwise use the standard name
          PATTERN="${{ inputs.STACK != '' && format('{0}-storagedocsbucketepsamdocs', inputs.STACK) || 'epsam-storagedocsbucketepsamdocs' }}"

          echo "Searching for bucket with pattern: $PATTERN"
          ./find_bucket.sh "$PATTERN"

      - name: Check Discrepancies (Dry Run)
        id: compare
        run: |
          echo "Comparing local files with s3://${{ steps.find-destination-bucket.outputs.BUCKET }}..."
          # Capture the dry-run output to see what WOULD change
          DIFFS=$(aws s3 sync ./s3-content s3://${{ steps.find-destination-bucket.outputs.BUCKET }} --dryrun)

          if [ -z "$DIFFS" ]; then
            echo "No discrepancies found."
          else
            echo "::warning title=Discrepancy Found in ${{ inputs.TARGET_ENVIRONMENT }}::$DIFFS"
          fi

      - name: Upload Files to Target S3
        run: |
          aws s3 sync ./s3-content s3://${{ steps.find-destination-bucket.outputs.BUCKET }} --delete
