name: cdk release code

on:
  workflow_call:
    inputs:
      STACK_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      CDK_APP_NAME:
        required: true
        type: string
      DEPLOY_CODE:
        type: boolean
        default: false
      LOG_RETENTION_IN_DAYS:
        required: true
        type: string
      LOG_LEVEL:
        required: true
        type: string
      MARK_JIRA_RELEASED:
        type: boolean
        default: false
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
      CDK_PULL_IMAGE_ROLE:
        required: true
      DEV_CLOUD_FORMATION_CHECK_VERSION_ROLE:
        required: false
      DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE:
        required: false
      REGRESSION_TESTS_PEM:
        required: false
      SLACK_BOT_TOKEN:
        required: false
      SLACK_SIGNING_SECRET:
        required: false

jobs:
  release_code:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    name: deploy cdk app ${{ inputs.CDK_APP_NAME }}
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout local github actions
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
          sparse-checkout: |
            .github

      - name: Configure AWS Credentials
        id: connect-aws-pull-image
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CDK_PULL_IMAGE_ROLE }}
          role-session-name: eps-assist-me-pull-image

      - name: build_artifact download
        uses: actions/download-artifact@v4
        with:
          name: build_artifact
  
      - name: Extract build_artifact
        run: |
          mkdir -p .build
          tar -xf artifact.tar -C .build

      - name: Retrieve AWS Account ID
        id: retrieve-account-id
        run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_ENV"

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com

      - name: Pull cdk-utils-build from Amazon ECR
        run: |
          docker pull "${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/cdk-utils-build-repo:latest"
          docker tag "${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/cdk-utils-build-repo:latest" cdk-utils-build-repo:latest

      - name: Configure AWS Credentials
        id: connect-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: eps-assist-me-deployment
          output-credentials: true

      - name: fix cdk.json for deployment
        run: |
          ./.github/scripts/fix_cdk_json.sh
        env:
          ACCOUNT_ID: "${{ env.ACCOUNT_ID }}"
          STACK_NAME: "${{ inputs.STACK_NAME }}"
          VERSION_NUMBER: "${{ inputs.VERSION_NUMBER }}"
          COMMIT_ID: "${{ inputs.COMMIT_ID }}"
          LOG_RETENTION_IN_DAYS: "${{ inputs.LOG_RETENTION_IN_DAYS }}"
          LOG_LEVEL: "${{ inputs.LOG_LEVEL }}"
          SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
          SLACK_SIGNING_SECRET: "${{ secrets.SLACK_SIGNING_SECRET }}"

      - name: Show diff
        run: |
          docker run \
            -v "$(pwd)/.build":/home/cdkuser/workspace/ \
            -e AWS_ACCESS_KEY_ID=${{ steps.connect-aws.outputs.aws-access-key-id }} \
            -e AWS_SECRET_ACCESS_KEY=${{ steps.connect-aws.outputs.aws-secret-access-key }} \
            -e AWS_SESSION_TOKEN=${{ steps.connect-aws.outputs.aws-session-token }} \
            -e AWS_REGION="eu-west-2" \
            -e SHOW_DIFF="true" \
            -e DEPLOY_CODE="false" \
            -e CDK_APP_PATH="packages/cdk/bin/EpsAssistMeApp.ts" \
            cdk-utils-build-repo:latest

      - name: Deploy code
        if: ${{ inputs.DEPLOY_CODE == true }}
        run: |
          docker run \
            -v "$(pwd)/.build":/home/cdkuser/workspace/ \
            -e AWS_ACCESS_KEY_ID=${{ steps.connect-aws.outputs.aws-access-key-id }} \
            -e AWS_SECRET_ACCESS_KEY=${{ steps.connect-aws.outputs.aws-secret-access-key }} \
            -e AWS_SESSION_TOKEN=${{ steps.connect-aws.outputs.aws-session-token }} \
            -e AWS_REGION="eu-west-2" \
            -e SHOW_DIFF="false" \
            -e DEPLOY_CODE="true" \
            -e CDK_APP_PATH="packages/cdk/bin/EpsAssistMeApp.ts" \
            cdk-utils-build-repo:latest
        shell: bash

      - name: mark_released_in_jira
        uses: ./.github/actions/mark_jira_released
        if: ${{ inputs.MARK_JIRA_RELEASED == true && always() && !failure() && !cancelled() }}
        with:
          RELEASE_TAG: ${{ inputs.VERSION_NUMBER }}
          DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}

      - name: Checkout gh-pages
        if: ${{ !startsWith(inputs.STACK_NAME, 'epsam-pr-') }}
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update release tag in github pages
        if: ${{ !startsWith(inputs.STACK_NAME, 'epsam-pr-') }}
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          echo "${{ inputs.VERSION_NUMBER }},${NOW}" >> _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          echo "${{ inputs.VERSION_NUMBER }},${NOW}" >> _data/${{ inputs.TARGET_ENVIRONMENT }}_deployments.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          git add _data/${{ inputs.TARGET_ENVIRONMENT }}_deployments.csv
          git commit -m 'update releases for ${{ inputs.TARGET_ENVIRONMENT }}'
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"
